import 'package:flutter/material.dart';

List carNames = [
  'Audi',
  'Chevrolet',
  'Cadillac',
  'Acura',
  'BMW',
  'Chrysler',
  'Ford',
  'Buick',
  'GMC',
  'Honda',
  'Hyundai',
  'Jeep',
  'Genesis',
  'Dodge',
  'Jaguar',
  'Kia',
  'Land Rover',
  'Lexus',
  'Mercedes - Benz',
  'Mitsubishi',
  'Lincoln',
  'MAZDA',
  'Nissan',
  'MINI',
  'Porsche',
  'Ram',
  'Subaru',
  'Toyota',
  'Volkswagen',
  'Volvo',
  'FIAT',
  'Freightliner',
  'Ferrari',
  'Lamborghini',
  'McLaren',
  'Rolls - Royce',
  'Suzuki',
  'Fisker',
  'Maybach',
  'Mercury',
  'Saab',
  'Pontiac',
  'Saturn',
  'Isuzu',
  'Panoz',
  'Oldsmobile',
  'Daewoo',
  'Plymouth',
  'Eagle',
  'Geo',
  'Daihatsu'
];

Map carModel = {
  'Audi': [
    'A7',
    'TT',
    'RS 3',
    'A6',
    'A3 Sportback e - tron',
    'R8',
    'A4',
    'A3',
    'Q7',
    'SQ5',
    'Q3',
    'A8',
    'RS 7',
    'S3',
    'Q5',
    'A5',
    'S5',
    'A4 allroad',
    'S6',
    'S8',
    'e - tron',
    'RS 5',
    'S4',
    'Q8',
    'A5 Sport',
    'S7',
    'allroad',
    'RS 4',
    'A4(2005.5)',
    'S4(2005.5)',
    'RS 6',
    'Cabriolet',
    '100',
    '90',
    'Quattro',
    '80'
  ],
  'Chevrolet': [
    'Colorado Crew',
    'Silverado 3500 HD Crew',
    'Bolt EV',
    'Malibu',
    'Camaro',
    'Express 2500 Passenger',
    'Suburban 3500HD',
    'Silverado 1500 Regular',
    'Spark',
    'Silverado 1500 LD Double',
    'Silverado 2500 HD Double',
    'Impala',
    'Silverado 1500 Double Cab',
    'Express 3500 Cargo',
    'Blazer',
    'Tahoe',
    'Silverado 2500 HD Crew',
    'Silverado 1500 Crew',
    'Trax',
    'Traverse',
    'Volt',
    'Colorado Extended Cab',
    'Corvette',
    'Suburban',
    'Sonic',
    'Silverado 2500 HD Regular',
    'Silverado 3500 HD Double',
    'Express 3500 Passenger',
    'Cruze',
    'Equinox',
    'Silverado 3500 HD Regular',
    'Express 2500 Cargo',
    'City Express',
    'SS',
    'Cruze Limited',
    'Malibu Limited',
    'Impala Limited',
    'Captiva Sport',
    'Spark EV',
    'Express 1500 Passenger',
    'Express 1500 Cargo',
    'Suburban 1500',
    'Silverado 1500 Extended',
    'Avalanche',
    'Suburban 2500',
    'Silverado 2500 HD Extended',
    'Silverado 3500 HD Extended',
    'Colorado Regular Cab',
    'Aveo',
    'HHR',
    'Cobalt',
    'TrailBlazer',
    'Uplander Cargo',
    'Malibu (Classic)',
    'Uplander Passenger',
    'Silverado (Classic) 3500 Crew',
  ],
  'Cadillac': [
    'XT4',
    'CT6',
    'Escalade ESV',
    'ATS',
    'Escalade',
    'CTS',
    'ATS - V',
    'SRX',
    'XT5',
    'XTS',
    'XT6',
    'CTS - V',
    'DTS',
    'STS',
    'ELR',
    'Escalade EXT',
    'CT6 - V',
    'CT5',
    'XLR',
    'DeVille',
    'Seville',
    'Catera',
    'Eldorado',
    'Fleetwood',
    'Allante',
    'Brougham',
    'Sixty Special'
  ],
  'Acura': [
    'RLX',
    'RLX Sport Hybrid',
    'MDX',
    'TLX',
    'RDX',
    'TSX',
    'TL',
    'ILX',
    'ZDX',
    'MDX Sport Hybrid',
    'NSX',
    'RL',
    'RSX',
    'Integra',
    'CL',
    'SLX',
    'Legend',
    'Vigor'
  ],
  'BMW': [
    'i3',
    'X6',
    'X6' 'M',
    '3 Series',
    '7 Series',
    '5 Series',
    '2 Series',
    '6 Series',
    'X4',
    'X5',
    '4 Series',
    'X2',
    'X7',
    'M2',
    'X5 M',
    'M6',
    'X1',
    'M5',
    'X3',
    'i8',
    'M3',
    'M4',
    '8 Series',
    'Z4',
    '1 Series',
    'Alpina B7',
    'Z4 M',
    'Z8',
    'Z3',
    'M'
  ],
  'Chrysler': [
    'Pacifica',
    '200',
    'Pacifica Hybrid',
    '300',
    'Crossfire',
    'Voyager',
    'Town & Country',
    'Sebring',
    'Concorde',
    'PT Cruiser',
    'LHS',
    '300M',
    'Grand Voyager',
    'Aspen',
    'Cirrus',
    'Prowler',
    'New Yorker',
    'LeBaron',
    'Fifth Ave',
    'Imperial'
  ],
  'Ford': [
    'Endeavour',
    'Escape',
    'Flex',
    'Taurus',
    'Fusion',
    'F150 Regular',
    'F250 Super Duty Crew',
    'Fiesta',
    'Ranger SuperCrew',
    'C-MAX Hybrid',
    'Expedition MAX',
    'F350 Super Duty Crew',
    'Ranger SuperCab',
    'Explorer',
    'F450 Super Duty Crew',
    'F350 Super Duty Super',
    'F250 Super Duty Regular',
    'Transit Connect Passenger',
    'F150 SuperCrew',
    'Transit Connect Cargo',
    'Transit 250 Van',
    'Edge',
    'F150 Super',
    'EcoSport',
    'Expedition',
    'Transit 150 Wagon',
    'C-MAX Energi',
    'Transit 350 Wagon',
    'F350 Super Duty Regular',
    'Focus',
    'Transit 350 HD Van',
    'Fusion Energi',
    'Mustang',
    'Transit 350 Van',
    'F250 Super Duty Super',
    'Transit 150 Van',
    'Expedition EL',
    'Focus ST',
    'E150 Passenger',
    'E150 Cargo',
    'E250 Cargo',
    'E350 Super Duty',
    'Ranger Regular Cab',
    'Ranger Super Cab',
    'Crown Victoria',
    'E150 Super Duty',
    'Explorer Sport Trac',
    'Taurus X',
    'E150 Super Duty Cargo',
    'E250 Super Duty Cargo',
    'Five Hundred',
    'Freestar Passenger',
    'Freestar Cargo',
    'Freestyle',
    'GT',
    'Excursion',
    'Thunderbird',
    'F150 (Heritage) Regular',
    'F150 (Heritage) Super',
    'Explorer Sport'
  ],
  'Buick': [
    'Encore',
    'Regal',
    'Regal Sportback',
    'LaCrosse',
    'Cascada',
    'Regal TourX',
    'Enclave',
    'Envision',
    'Rainier',
    'Verano',
    'Lucerne',
    'Park Avenue',
    'Century',
    'Terraza',
    'LeSabre',
    'Rendezvous',
    'Riviera',
    'Skylark',
    'Roadmaster'
  ],
  'GMC': [
    'Sierra 2500 HD Crew',
    'Acadia',
    'Savana 2500 Cargo',
    'Yukon',
    'Sierra 3500 HD Double',
    'Sierra 2500 HD Double',
    'Savana 3500 Cargo',
    'Sierra 1500 Limited Double',
    'Sierra 1500 Double',
    'Terrain',
    'Canyon Crew',
    'Savana 1500 Passenger',
    'Sierra 3500 HD Crew',
    'Sierra 3500 HD Regular',
    'Sierra 1500 Regular',
    'Yukon XL',
    'Canyon Extended',
    'Sierra 1500 Crew',
    'Savana 2500 Passenger',
    'Savana 3500 Passenger',
    'Sierra 2500 HD Regular',
    'Acadia Limited',
    'Savana 1500 Cargo',
    'Sierra 2500 HD Extended',
    'Yukon XL 1500',
    'Yukon XL 2500',
    'Sierra 1500 Extended',
    'Sierra 3500 HD Extended',
    'Canyon Regular Cab',
    'Envoy',
    'Sierra (Classic)' '1500 Regular',
    'Sierra (Classic) 2500 HD Crew',
    'Sierra (Classic) 1500 Crew',
    'Sierra (Classic) 2500 HD Regular',
    'Sierra (Classic) 2500 HD Extended',
    'Sierra (Classic) 3500 Regular',
    'Sierra (Classic) 1500 Extended',
    'Sierra (Classic) 1500 HD Crew',
    'Sierra (Classic) 3500 Extended',
    'Sierra (Classic) 3500 Crew',
    'Envoy XL',
    'Sierra 1500 HD Crew',
    'Sierra 3500 Crew'
  ],
  'Honda': [
    'Pilot',
    'Clarity Electric',
    'Clarity Fuel Cell',
    'Accord Hybrid',
    'HR-V',
    'Fit',
    'Odyssey',
    'Civic Type R',
    'Accord',
    'CR-V',
    'CR-Z',
    'Ridgeline',
    'Clarity Plug-in Hybrid',
    'Passport',
    'Civic',
    'Insight',
    'Crosstour',
    'Accord Crosstour',
    'Element',
    'S2000',
    'Prelude',
    'del Sol'
  ],
  'Hyundai': [
    'Ioniq Plug-in Hybrid',
    'Kona',
    'Venue',
    'Accent',
    'Tucson',
    'Ioniq Hybrid',
    'Elantra GT',
    'NEXO',
    'Santa Fe',
    'Sonata Hybrid',
    'Equus',
    'Tucson Fuel Cell',
    'Santa Fe XL',
    'Elantra',
    'Sonata',
    'Veloster',
    'Genesis Coupe',
    'Sonata Plug-in Hybrid',
    'Genesis',
    'Santa Fe Sport',
    'Palisade',
    'Azera',
    'Ioniq Electric',
    'Kona Electric',
    'Veracruz',
    'Tiburon',
    'XG350',
    'Entourage',
    'XG300',
    'Scoupe',
    'Excel'
  ],
  'Jeep': [
    'Wrangler Unlimited',
    'Compass',
    'Wrangler',
    'Patriot',
    'Grand Cherokee',
    'Cherokee',
    'Renegade',
    'Commander',
    'Gladiator',
    'Liberty',
    'Comanche Regular Cab'
  ],
  'Genesis': ['G80', 'G70', 'G90'],
  'Dodge': [
    'Grand Caravan Passenger',
    'Durango',
    'Challenger',
    'Journey',
    'Charger',
    'Nitro',
    'Viper',
    'Dart',
    'Ram 3500 Crew',
    'Ram 1500 Quad',
    'Avenger',
    'Ram 1500 Regular',
    'Dakota Extended',
    'Caliber',
    'Ram 2500 Crew',
    'Ram 3500 Regular',
    'Dakota Crew',
    'Ram 2500 Mega',
    'Ram 2500 Regular',
    'Grand Caravan Cargo',
    'Ram 1500 Crew',
    'Ram 3500 Mega',
    'Ram 3500 Quad',
    'Ram 2500 Quad',
    'Sprinter 2500 Cargo',
    'Sprinter 2500 Passenger',
    'Caravan Cargo',
    'Magnum',
    'Sprinter 3500 Cargo',
    'Ram 1500 Mega',
    'Caravan Passenger',
    'Dakota Club',
    'Dakota Quad',
    'Stratus',
    'Neon',
    'Dakota Regular',
    'Intrepid',
    'Ram Van 2500',
    'Ram Van 1500',
    'Ram Van 3500',
    'Ram Wagon 2500',
    'Ram Wagon 1500',
    'Ram Wagon 3500',
    'Ram 1500 Club',
    'Ram 2500 Club',
    'Ram 3500 Club',
    'Stealth',
    'Ram Van B350',
    'Spirit',
    'Ram Van B250',
    'Colt',
    'Ram Van B150',
    'Ram Wagon B250',
    'Ram Wagon B150',
    'Shadow',
    'Ram Wagon B350',
    'D150 Club',
    'D250 Regular',
    'D150 Regular',
    'Daytona',
    'D250 Club',
    'D350 Club',
    'Dynasty',
    'D350 Regular',
    'Ramcharger'
  ],
  'Jaguar': [
    'F-TYPE',
    'XK',
    'F-PACE',
    'XJ',
    'XE',
    'I-PACE',
    'XF',
    'X-Type',
    'S-Type',
    'E-PACE'
  ],
  'Kia': [
    'Kia Sonet',
    'Kia Seltos',
    'Kia Carnival',
    'Kia Rio',
  ],
  'Land Rover': [
    'Land Rover Range Rover Sport',
    'Land Rover Range Rover Evoque',
    'Land Rover Range Rover Velar',
    'Land Rover Discovery Sport',
    'Land Rover Range Rover',
    'Land Rover Defender',
    'Land Rover Discovery',
  ],
  'Lexus': [
    'RX',
    'LC',
    'LS',
    'UX',
    'GS',
    'GX',
    'CT',
    'IS',
    'NX',
    'ES',
    'LX',
    'RC',
    'LFA',
    'IS F',
    'HS',
    'SC'
  ],
  'Mercedes': [
    'Mercedes-Benz C-Class',
    'Mercedes-Benz S-Class',
    'Mercedes-Benz E-Class',
    'Mercedes-Benz GLE',
    'Mercedes-Benz GLS',
    'Mercedes-Benz G-Class',
    'Mercedes-Benz V-Class',
    'Mercedes-Benz AMG GLE 53',
    'Mercedes-Benz AMG GT',
    'Mercedes-Benz EQC',
    'Mercedes-Benz CLS',
    'Mercedes-Benz GLC Coupe',
    'Mercedes-Benz A-Class Sedan',
    'Mercedes-Benz CLA 2020'
  ],
  'Mitsubishi': [
    'Mirage',
    'Mirage G4',
    'Outlander',
    'Outlander PHEV',
    'Outlander Sport',
    'Eclipse Cross',
    'Lancer',
    'Eclipse',
    'Galant',
    'i-MiEV',
    'Raider Extended Cab',
    'Raider Double Cab',
    'Endeavor',
    'Montero',
    'Montero Sport',
    'Diamante',
    'Lancer Evolution',
    '3000GT',
    'Mighty Max Regular Cab',
    'Expo',
    'Mighty Max Macro Cab',
    'Precis'
  ],
  'Lincoln': [
    'MKX',
    'Navigator',
    'MKZ',
    'Aviator',
    'MKT',
    'Continental',
    'Corsair',
    'Navigator L',
    'MKS',
    'MKC',
    'Nautilus',
    'Town Car',
    'Zephyr',
    'LS',
    'Mark LT',
    'Blackwood',
    'Mark VIII',
    'Mark VII'
  ],
  'MAZDA': [
    'MX-5 Miata',
    'CX-5',
    'CX-9',
    'MX-5 Miata RF',
    'MAZDA5',
    'CX-3',
    'CX-30',
    'MAZDA3',
    'MAZDA6',
    'MAZDA2',
    'B-Series Extended Cab',
    'Tribute',
    'CX-7',
    'RX-8',
    'B-Series Regular Cab',
    'B-Series Cab Plus',
    'MPV',
    'Protege5',
    'Protege',
    'Millenia',
    '626',
    '929',
    'MX-6',
    'MX-3',
    '323',
    'RX-7',
    'Navajo'
  ],
  'Nissan': [
    'NV3500 HD Cargo',
    'Armada',
    'Rogue',
    'Frontier Crew Cab',
    'NV2500 HD Cargo',
    'TITAN XD Single Cab',
    'Frontier King Cab',
    'Altima',
    '370Z',
    'Murano',
    'NV3500 HD Passenger',
    'TITAN XD Crew Cab',
    'GT-R',
    'TITAN XD King Cab',
    'Sentra',
    'Kicks',
    'Pathfinder',
    'NV1500 Cargo',
    'Maxima',
    'NV200',
    'Versa',
    'LEAF',
    'Titan Crew Cab',
    'Titan King Cab',
    'Rogue Sport',
    'TITAN Single Cab',
    'Versa Note',
    'JUKE',
    'NV200 Taxi',
    'Quest',
    'Rogue Select',
    'Xterra',
    'cube',
    '350Z',
    'Pathfinder Armada',
    'Frontier Regular Cab',
    '240SX',
    '200SX',
    '300ZX',
    'Regular Cab',
    'King Cab',
    'NX',
    'Stanza'
  ],
  'MINI': [
    'Mini Cooper Convertible',
    'Mini Countryman',
    'Mini Cooper 3 DOOR',
    'Mini JCW',
    'Mini Oxford',
    'Mini Clubman',
  ],
  'Porsche': [
    'Macan',
    '718 Cayman',
    'Boxster',
    'Taycan',
    'Panamera',
    '911',
    'Cayenne',
    '718 Boxster',
    'Cayman',
    'Carrera GT',
    'Cayenne Coupe',
    '928'
  ],
  'Ram': [
    '1500 Quad Cab',
    '2500 Crew Cab',
    '2500 Regular Cab',
    '3500 Crew Cab',
    'ProMaster Window Van',
    '2500 Mega Cab',
    '3500 Regular Cab',
    '1500 Regular Cab',
    'ProMaster Cargo Van',
    '1500 Crew Cab',
    '1500 Classic Regular Cab',
    'ProMaster City',
    'C/V Tradesman',
    '3500 Mega Cab',
    '1500 Classic Quad Cab',
    '1500 Classic Crew Cab',
    'ProMaster 1500 Cargo',
    'ProMaster 3500 Cargo',
    'ProMaster 2500 Cargo',
    'C/V',
    'Dakota Extended Cab',
    'Dakota Crew Cab'
  ],
  'Subaru': [
    'Legacy',
    'Forester',
    'BRZ',
    'Ascent',
    'WRX',
    'Outback',
    'Crosstrek',
    'Impreza',
    'Tribeca',
    'XV Crosstrek',
    'Baja',
    'B9 Tribeca',
    'Justy',
    'SVX',
    'Loyale'
  ],
  'Toyota': [
    'Tacoma Double Cab',
    'GR Supra',
    'RAV4 Hybrid',
    'Sequoia',
    'Corolla',
    'Camry Hybrid',
    'Highlander Hybrid',
    'Tacoma Access Cab',
    'Avalon',
    'RAV4',
    'Mirai',
    'Corolla Hybrid',
    'Yaris',
    '4Runner',
    'Highlander',
    'Yaris Hatchback',
    'Corolla Hatchback',
    'Prius Prime',
    'Tundra CrewMax',
    'Tundra Double Cab',
    'Prius',
    'Avalon Hybrid',
    '86',
    'C-HR',
    'Sienna',
    'Yaris iA',
    'Prius v',
    'Prius c',
    'Land Cruiser',
    'Camry',
    'Corolla iM',
    'Tundra Regular Cab',
    'Prius Plug-in Hybrid',
    'FJ Cruiser',
    'Tacoma Regular Cab',
    'Venza',
    'Matrix',
    'Solara',
    'Tundra Access Cab',
    'Echo',
    'Celica',
    'MR2',
    'Tacoma Xtracab',
    'T100 Regular Cab',
    'Previa',
    'T100 Xtracab',
    'Tercel',
    'Supra',
    'Paseo',
    'Regular Cab',
    'Xtra Cab',
    'Cressida'
  ],
  'Volkswagen': [
    'Atlas',
    'Golf GTI',
    'Beetle',
    'Golf',
    'Tiguan',
    'CC',
    'Jetta',
    'Golf R',
    'Touareg',
    'Golf SportWagen',
    'Golf Alltrack',
    'Passat',
    'Routan',
    'Eos',
    'Jetta GLI',
    'Tiguan Limited',
    'e-Golf',
    'Jetta SportWagen',
    'Arteon',
    'GTI',
    'New Beetle',
    'Touareg 2',
    'R32',
    'Rabbit',
    'GLI',
    'Phaeton',
    'Jetta (New)',
    'Eurovan',
    'Cabrio',
    'Golf (New)',
    'Passat (New)',
    'GTI (New)',
    'Cabrio (New)',
    'Golf III',
    'Jetta III',
    'Corrado',
    'Cabriolet',
    'Fox'
  ],
  'Volvo': [
    'XC60',
    'V60',
    'XC90',
    'S90',
    'XC40',
    'S60',
    'C70',
    'C30',
    'S80',
    'V90',
    'S40',
    'V70',
    'XC70',
    'V50',
    'S40 (New)',
    'V40',
    'S70',
    '850',
    '960',
    '940',
    '240',
    '740'
  ],
  'FIAT': [
    'Fiat Abarth 595',
    'Fiat Abarth Punto',
    'Fiat Linea',
    'Fiat Avventura',
    'Fiat Urban Cross',
    'Fiat Linea Classic',
    'Fiat Punto Evo',
    'Fiat Punto Pure',
  ],
  'Freightliner': [
    'Sprinter 2500 Crew',
    'Sprinter 3500 Cargo',
    'Sprinter 3500XD Cargo',
    'Sprinter 2500 Cargo',
    'Sprinter WORKER Cargo',
    'Sprinter 2500 Passenger',
    'Sprinter WORKER Passenger'
  ],
  'Ferrari': [
    '488 Spider',
    'Portofino',
    'F12berlinetta',
    'FF',
    'California',
    '458 Spider',
    '488 GTB',
    '458 Italia',
    '430 Scuderia',
    'GTC4Lusso',
    '612 Scaglietti',
    '599 GTB Fiorano',
    '812 Superfast',
    '599 GTO',
    '458 Speciale',
    'F430'
  ],
  'Lamborghini': [
    'Aventador',
    'Huracan',
    'Murcielago',
    'Gallardo',
    'Murcielago LP640'
  ],
  'McLaren': ['570S', '570GT', '650S', 'MP4-12C', '720S', '675LT'],
  'Rolls - Royce': [
    'Phantom',
    'Phantom Drophead Coupe',
    'Phantom Coupé',
    'Ghost',
    'Wraith',
    'Dawn',
    'Sweptail(one-off)',
    'Phantom'
  ],
  'Suzuki': [
    'Swift',
    'Baleno',
    'Ertiga',
    'Vitara Brezza',
    'Dzire',
    'Alto',
    'Wagon R',
    'Celerio',
    'Ciaz',
    'Celerio X',
    'XL6',
    'S-Cross',
    'S-Presso',
    'Eeco',
    'Ignis',
    'Ritz'
  ],
  'Fisker': ['Karma'],
  'Maybach': ['57', '62'],
  'Mercury': [
    'Milan',
    'Grand Marquis',
    'Sable',
    'Mariner',
    'Mountaineer',
    'Monterey',
    'Villager',
    'Cougar',
    'Capri',
    'Montego',
    'Marauder',
    'Mystique',
    'Tracer',
    'Topaz'
  ],
  'Saab': ['9-7X', '3-Sep', '5-Sep', '9-4X', '900', '9-2X', '9000'],
  'Pontiac': [
    'G6',
    'G3',
    'G6 (2009.5)',
    'Aztek',
    'Bonneville',
    'Montana',
    'G8',
    'Grand Prix',
    'Solstice',
    'Montana SV6',
    'Torrent',
    ' Sunfire',
    'Firebird',
    'G5',
    'Grand Am',
    'Vibe',
    'GTO',
    'Trans Sport',
    'LeMans',
    'Sunbird'
  ],
  'Saturn': [
    'VUE',
    'Aura',
    'L-Series',
    'Relay',
    'Ion',
    'S-Series',
    'Outlook',
    'SKY',
    'Astra'
  ],
  'Isuzu': [
    'Ascender',
    'i-350 Crew Cab',
    'Axiom',
    'Rodeo',
    'Amigo',
    'i-370 Crew Cab',
    'i-370 Extended Cab',
    'Rodeo Sport',
    'i-280 Extended Cab',
    'VehiCROSS',
    'Regular Cab',
    'Spacecab',
    'i-290 Extended Cab',
    'Trooper',
    'Oasis',
    'Hombre Regular Cab',
    'Hombre Spacecab',
    'Impulse',
    'Stylus'
  ],
  'Panoz': ['Esperante'],
  'Oldsmobile': [
    'Silhouette',
    'Alero',
    'Aurora',
    '88',
    'Bravada',
    'Cutlass',
    'Achieva',
    'Cutlass',
    'Ciera',
    'Intrigue',
    '98',
    'LSS',
    'Regency',
    'Cutlass Supreme',
    'Custom Cruiser',
    'Cutlass Cruiser',
    'Ciera',
    'Toronado'
  ],
  'Daewoo': ['Nubira', 'Lanos', 'Leganza'],
  'Plymouth': [
    'Voyager',
    'Breeze',
    'Prowler',
    'Grand Voyager',
    'Neon',
    'Colt',
    'Sundance',
    'Acclaim',
    'Colt Vista',
    'Laser'
  ],
  'Eagle': ['Talon', 'Summit', 'Vision', 'Premier'],
  'Geo': ['Metro', 'Prizm', 'Tracker', 'Storm'],
  'Daihatsu': ['Charade', 'Rocky']
};

List<String> pinCodes = [
  '302001',
  '302005',
  '302006',
  '302007',
  '302009',
  '302010',
  '302011',
  '302015',
  '302016',
  '302017',
  '302018',
  '302019',
  '302020',
  '302021',
  '302022',
  '302023',
  '302024',
  '302025',
  '302026',
  '302029',
  '302030',
  '302033',
  '302035',
  '302039',
  '302003',
  '302004',
  '302012',
  '302013',
  '303033'
];

List<DropdownMenuItem> pinCodesDropDownList = [
  DropdownMenuItem(
    child: const Text(
      'PinCode',
      style: const TextStyle(
          fontFamily: 'Nunito',
          fontSize: 16,
          fontWeight: FontWeight.w600,
          color: Colors.black),
    ),
    value: 0,
  ),
  DropdownMenuItem(
    child: const Text(
      '302001',
      style: const TextStyle(
          fontFamily: 'Nunito',
          fontSize: 16,
          fontWeight: FontWeight.w600,
          color: Colors.black),
    ),
    value: 1,
  ),
  DropdownMenuItem(
    child: const Text(
      '302005',
      style: const TextStyle(
          fontFamily: 'Nunito',
          fontSize: 16,
          fontWeight: FontWeight.w600,
          color: Colors.black),
    ),
    value: 2,
  ),
  DropdownMenuItem(
    child: const Text(
      '302006',
      style: const TextStyle(
          fontFamily: 'Nunito',
          fontSize: 16,
          fontWeight: FontWeight.w600,
          color: Colors.black),
    ),
    value: 3,
  ),
  DropdownMenuItem(
    child: const Text(
      '302007',
      style: const TextStyle(
          fontFamily: 'Nunito',
          fontSize: 16,
          fontWeight: FontWeight.w600,
          color: Colors.black),
    ),
    value: 4,
  ),
  DropdownMenuItem(
    child: const Text(
      '302009',
      style: const TextStyle(
          fontFamily: 'Nunito',
          fontSize: 16,
          fontWeight: FontWeight.w600,
          color: Colors.black),
    ),
    value: 5,
  ),
  DropdownMenuItem(
    child: const Text(
      '302010',
      style: const TextStyle(
          fontFamily: 'Nunito',
          fontSize: 16,
          fontWeight: FontWeight.w600,
          color: Colors.black),
    ),
    value: 6,
  ),
  DropdownMenuItem(
    child: const Text(
      '302011',
      style: const TextStyle(
          fontFamily: 'Nunito',
          fontSize: 16,
          fontWeight: FontWeight.w600,
          color: Colors.black),
    ),
    value: 7,
  ),
  DropdownMenuItem(
    child: const Text(
      '302015',
      style: const TextStyle(
          fontFamily: 'Nunito',
          fontSize: 16,
          fontWeight: FontWeight.w600,
          color: Colors.black),
    ),
    value: 8,
  ),
  DropdownMenuItem(
    child: const Text(
      '302016',
      style: const TextStyle(
          fontFamily: 'Nunito',
          fontSize: 16,
          fontWeight: FontWeight.w600,
          color: Colors.black),
    ),
    value: 9,
  ),
  DropdownMenuItem(
    child: const Text(
      '302017',
      style: const TextStyle(
          fontFamily: 'Nunito',
          fontSize: 16,
          fontWeight: FontWeight.w600,
          color: Colors.black),
    ),
    value: 10,
  ),
  DropdownMenuItem(
    child: const Text(
      '302018',
      style: const TextStyle(
          fontFamily: 'Nunito',
          fontSize: 16,
          fontWeight: FontWeight.w600,
          color: Colors.black),
    ),
    value: 11,
  ),
  DropdownMenuItem(
    child: const Text(
      '302019',
      style: const TextStyle(
          fontFamily: 'Nunito',
          fontSize: 16,
          fontWeight: FontWeight.w600,
          color: Colors.black),
    ),
    value: 12,
  ),
  DropdownMenuItem(
    child: const Text(
      '302020',
      style: const TextStyle(
          fontFamily: 'Nunito',
          fontSize: 16,
          fontWeight: FontWeight.w600,
          color: Colors.black),
    ),
    value: 13,
  ),
  DropdownMenuItem(
    child: const Text(
      '302021',
      style: const TextStyle(
          fontFamily: 'Nunito',
          fontSize: 16,
          fontWeight: FontWeight.w600,
          color: Colors.black),
    ),
    value: 14,
  ),
  DropdownMenuItem(
    child: const Text(
      '302022',
      style: const TextStyle(
          fontFamily: 'Nunito',
          fontSize: 16,
          fontWeight: FontWeight.w600,
          color: Colors.black),
    ),
    value: 15,
  ),
  DropdownMenuItem(
    child: const Text(
      '302023',
      style: const TextStyle(
          fontFamily: 'Nunito',
          fontSize: 16,
          fontWeight: FontWeight.w600,
          color: Colors.black),
    ),
    value: 16,
  ),
  DropdownMenuItem(
    child: const Text(
      '302024',
      style: const TextStyle(
          fontFamily: 'Nunito',
          fontSize: 16,
          fontWeight: FontWeight.w600,
          color: Colors.black),
    ),
    value: 17,
  ),
  DropdownMenuItem(
    child: const Text(
      '302025',
      style: const TextStyle(
          fontFamily: 'Nunito',
          fontSize: 16,
          fontWeight: FontWeight.w600,
          color: Colors.black),
    ),
    value: 18,
  ),
  DropdownMenuItem(
    child: const Text(
      '302026',
      style: const TextStyle(
          fontFamily: 'Nunito',
          fontSize: 16,
          fontWeight: FontWeight.w600,
          color: Colors.black),
    ),
    value: 19,
  ),
  DropdownMenuItem(
    child: const Text(
      '302029',
      style: const TextStyle(
          fontFamily: 'Nunito',
          fontSize: 16,
          fontWeight: FontWeight.w600,
          color: Colors.black),
    ),
    value: 20,
  ),
  DropdownMenuItem(
    child: const Text(
      '302030',
      style: const TextStyle(
          fontFamily: 'Nunito',
          fontSize: 16,
          fontWeight: FontWeight.w600,
          color: Colors.black),
    ),
    value: 21,
  ),
  DropdownMenuItem(
    child: const Text(
      '302033',
      style: const TextStyle(
          fontFamily: 'Nunito',
          fontSize: 16,
          fontWeight: FontWeight.w600,
          color: Colors.black),
    ),
    value: 22,
  ),
  DropdownMenuItem(
    child: const Text(
      '302035',
      style: const TextStyle(
          fontFamily: 'Nunito',
          fontSize: 16,
          fontWeight: FontWeight.w600,
          color: Colors.black),
    ),
    value: 23,
  ),
  DropdownMenuItem(
    child: const Text(
      '302039',
      style: const TextStyle(
          fontFamily: 'Nunito',
          fontSize: 16,
          fontWeight: FontWeight.w600,
          color: Colors.black),
    ),
    value: 24,
  ),
  DropdownMenuItem(
    child: const Text(
      '302003',
      style: const TextStyle(
          fontFamily: 'Nunito',
          fontSize: 16,
          fontWeight: FontWeight.w600,
          color: Colors.black),
    ),
    value: 25,
  ),
  DropdownMenuItem(
    child: const Text(
      '302004',
      style: const TextStyle(
          fontFamily: 'Nunito',
          fontSize: 16,
          fontWeight: FontWeight.w600,
          color: Colors.black),
    ),
    value: 26,
  ),
  DropdownMenuItem(
    child: const Text(
      '302012',
      style: const TextStyle(
          fontFamily: 'Nunito',
          fontSize: 16,
          fontWeight: FontWeight.w600,
          color: Colors.black),
    ),
    value: 27,
  ),
  DropdownMenuItem(
    child: const Text(
      '302013',
      style: const TextStyle(
          fontFamily: 'Nunito',
          fontSize: 16,
          fontWeight: FontWeight.w600,
          color: Colors.black),
    ),
    value: 28,
  ),
  DropdownMenuItem(
    child: const Text(
      '303033',
      style: const TextStyle(
          fontFamily: 'Nunito',
          fontSize: 16,
          fontWeight: FontWeight.w600,
          color: Colors.black),
    ),
    value: 29,
  ),
];
